language: python
python:
- 3.5
before_install:
- sudo apt-get update
- sudo apt-get -y install python-pip
- sudo pip install --upgrade pip
- pip install --upgrade pip
- pip install pycodestyle
- pip install autopep8
deploy:
  - provider: script
  - script: bash scripts/style.sh
  - on:
      branch: master
