language: python
python:
- 3.5
before_install:
- sudo apt-get update
- sudo apt-get -y install python-pip
- sudo pip install --upgrade pip
- pip install --upgrade pip
- pip install pycodestyle
- pip install autopep8
- pip install twine

script:
  - AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - |
    if ($AUTHOR_NAME == 'TravisMooreBot'); then
      set +e
      exit 0
    fi
  # run tests
  - python -m unittest -s moore_math_beta -p 'test_*.py'
  # fix style
  - num_errors_before=`find . -name \*.py -exec pycodestyle --ignore=E402 {} + | wc -l`
  - echo $num_errors_before
  - find . -name \*.py -exec autopep8 --recursive --aggressive --aggressive --in-place {} +
  - num_errors_after=`find . -name \*.py -exec pycodestyle --ignore=E402 {} + | wc -l`
  - echo $num_errors_after
  # run build 
  - cd "$TRAVIS_BUILD_DIR"
  - python setup.py sdist bdist_wheel
  - twine upload -u __token__ -p $TRAVIS_PASS dist/*

  - cd "$TRAVIS_BUILD_DIR"
  - git config --global user.email "suriabhinav1997@gmail.com"
  - git config --global user.name "TravisMooreBot"
  - git checkout $TRAVIS_BRANCH

  # push the files to master
  - |
    if (( $num_errors_after < $num_errors_before )); then
      git commit -a -m "PEP-8 Fix"
      git config --global  simple # Push only to the current branch.  
      # Make sure to make the output quiet, or else the API token will 
      # leak!  This works because the API key can replace your password.
      git push -f -q https://$GITHUB_API_KEY@github.com/abhisuri97/moore-math-beta.git master > /dev/null
    fi
